matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
    - os: linux
      dist: xenial
      sudo: required
    - os: osx
      osx_image: xcode9.4
env:
  - SWIFT_VER=4.03
  - SWIFT_VER=4.1
before_install:
  - chmod +x ./scripts/install-swift.sh
install: ./scripts/install-swift.sh
script:
  - swift --version
#- . ~/.swiftenv/init
#- swift build