matrix:
  include:
    - os: linux
      dist: xenial
      env:
        - SWIFT_VER=4.03
        - SWIFTENV_ROOT=$HOME/.swiftenv
        - PATH=$SWIFTENV_ROOT/bin:$PATH
    - os: linux
      dist: xenial
      env:
        - SWIFT_VER=4.1
        - SWIFTENV_ROOT=$HOME/.swiftenv
        - PATH=$SWIFTENV_ROOT/bin:$PATH
    - os: osx
      osx_image: xcode9.4
      language: generic
sudo: required
language: generic
before_install:
  - chmod +x ./scripts/install-swift.sh
install: ./scripts/install-swift.sh
script:
  - swift --version
#- . ~/.swiftenv/init
#- swift build